name: more
channels:
  - defaults
dependencies:
  - python=3.8.20
  - tensorboard
  - pip:
      - pybullet
      - pydelatin
      - pyfqmr
      - transforms3d
      - pytorch3d
      - warp-lang
      - opencv-python
      - wandb
